### ISSUE TITLE
testing session 2

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#201]
- [x] experiment turning off the line of sight/180 vision
- [ ] monsters not wandering properly, going back and forth (stuck?)
  also civilians not working
- [ ] better way of looking around
- [ ] orange player names?
- [ ] Make all healing items (Apples, etc) to give atleast 5 health points, otherwise they are useless
- [ ] bad level design in tutorial if you jump down, make sure there are no areas where you can get stuck in (also ending spot, last arrow)
- [x] There are too little navigation nodes! A lot of NPCs are bugging or frozen in place because they have very little knowledge of the surroundings
- [ ] all weapons must shoot faster, it feels very laggy currently and unresponsive. Make all weapons x2 speed? Or atleast make the slowest ones faster.
- [x] The item tooltip stays if you use an item or if you loot a moneybag
- [x] Make loot more interesting/add more items. no more dull sword drops
- [x] add the profanity filter on usernames
- [x] investigate "slowness" reported by a lot of players
- [x] remove (old) navigation nodes that were not placed using the scanner
- [ ] remove code that makes players unable to move on steep hills, annoys more people than it helps them (see LP IB 3)
- [ ] "You start out naked - that's pretty weird"
- [ ] "They're wooden leggings, but they're pink" remove wooden armor, replace it by leather?
- [x] We want a bank
- [x] server crash:
- [x] removing health regen
- [ ] investigate memory leak
- [ ] investigate monsters not respawing after attacking/killing them
- [ ] When moving around an object while targeting it, the targeting icon will stay in place and not rotate with the character, so as a result, there is a 180 degree range in which the circle will not show.
- [ ] When equipping armor, if you drop it while it is equipped, it will remain graphically on your character (stats are set correctly).
- [ ] When moving, sometimes I experience movements being "locked" and I can only stop when I press the key again. For example, if I hit the E key, and press other keys, the E motion will sometimes get stuck.
- [ ] Objects are poorly optimized. Not sure how else to word this, but anywhere there is a large population of NPCs, projectiles, item bags, or any combination, frame rate drops dramatically. Eric was PMing Nick directly, since because of this the rat area is almost unplayable.
- [ ] Occasionally, dropping equippable items will cause their icon to appear in the top left corner at 0,0. I've had trouble reproducing this one because it only happens sometimes.
- [ ] On coming back from another tab, all projectiles will suddenly appear as if they have been backed up in the system. I think that they should have a date stamp so that these waves don't simply crash clients who come back after a while.
- [ ] Characters still bounce over the land similar to the bug where when NPCs didn't have land underneath them, they would suddenly appear much higher and fall, repeating the process.
  Oct 00:11:43 - Toibj was killed by a Ghost

```
timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
TypeError: Cannot read property 'x' of undefined
    at THREE.Vector3.sub (eval at start (/ibserver/production_b/main.js:188:47))
    at VectorDistance (eval at start (/ibserver/production_b/main.js:188:47))
    at Class.State.extend.Execute (eval at start (/ibserver/production_b/main.js:188:47))
    at Class.extend.Update (eval at start (/ibserver/production_b/main.js:188:47))
    at Class.MovingUnit.extend.Tick (eval at start (/ibserver/production_b/main.js:188:47))
    at Class.extend.prototype.(anonymous function) (eval at start (/ibserver/production_b/main.js:188:47))
    at Class.Actor.extend.Tick (eval at start (/ibserver/production_b/main.js:188:47))
    at Class.extend.prototype.(anonymous function) (eval at start (/ibserver/production_b/main.js:188:47))
```
- [ ] the night is ugly and needs stars. The world at night looks uninteresting
- [ ] implement light mapping
- [ ] add all models made by 3d modelers, also on forums (whats wrong with the statue?)
- [ ] shadows in dungeons
- [ ] cookie set for a month not working, still forgets login sometimes? (needs more testing)
- [x] arrows seems to keep raycasting even after landed
- [ ] female sprites' eyes need two pixels in height
- [x] it is possible to register multiple accounts with the same name :P
- [ ] transparent sprite show the loading text behind webgl canvas?
- [ ] world entrance surrounding area: add monsters, too boring currently. guide the players what to do there. 
- [ ] town is a ghost town: no npcs; nothing is happening and super boring. houses are empty... needs a lot of work
- [ ] houses all look the same

**Comment by bsparks** [comment]
alternative to health items giving more health: lower/remove health regen (maybe a perk?)

**Comment by nickjanssen** [comment]
sounds good! We would like to add perks/quests next for 0.5

**Comment by ghost** [comment]
Suggestion: add a sign in the tutorial mentioning faster turn rates while holding shift (perhaps around the area with slime turrets?). I had no idea I could do that until someone mentioned it.

**Comment by ghost** [comment]
Is anything from here in game? Spears? http://www.ironbane.com/forum.php?action=topic&topic=613

Spears would be a nice addition. Since you did say "Make loot more interesting/add more items. no more dull sword drops"

**Comment by ChaiTeaNunes** [comment]
Try to make it so when you hit slash, it opens the chat.

**Comment by ghost** [comment]
I do second that. Many games simply have the slash key open when it is pressed for quick commands.

**Comment by ChaiTeaNunes** [comment]
Like Minecraft ;)

**Comment by bsparks** [comment]
added / and @ to open the chat.

**Comment by ChaiTeaNunes** [comment]
Thanks :+1:
