### ISSUE TITLE
Why does Ironbane require SUPER privileges?

### ISSUE THREAD

**Issue by markfarrell** [ironbane/IronbaneServerLegacy#367]
When I actually run IronbaneServer as well, it crashes because for some query operation Ironbane seems to require SUPER privileges; I can't pinpoint where. My MySQL account does not have SUPER privileges.

Is it really necessary for Ironbane to require SUPER privileges? 
How might I work around this?

`Error: ER_SPECIFIC_ACCESS_DENIED_ERROR: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
    at Query.Sequence._packetToError (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Sequence.js:32:14)
    at Query.ErrorPacket (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/Protocol.js:186:24)
    at Parser.write (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/Protocol.js:36:16)
    at Socket.ondata (stream.js:51:26)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    --------------------
    at Query.Sequence (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Sequence.js:15:20)
    at new Query (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Query.js:12:12)
    at Function.Connection.createQuery (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/Connection.js:47:10)
    at Connection.query (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/Connection.js:131:26)
    at Query._callback (/users/m4farrel/IronbaneServer/node_modules/connect-mysql/lib/connect-mysql.js:24:32)
    at Query.Sequence.end (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Sequence.js:75:24)
    at Query._handleFinalResultPacket (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.OkPacket (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/sequences/Query.js:77:10)
    at Protocol._parsePacket (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/Protocol.js:186:24)
    at Parser.write (/users/m4farrel/IronbaneServer/node_modules/mysql/lib/protocol/Parser.js:62:12)`

**Comment by bsparks** [comment]
there is one spot where it uses MySql EVENTs to monitor the cookies, which is part of a plugin, maybe that's it? (it's the connect-mysql in node modules / package.json)

works fine on my system tho (windows)

**Comment by lschans** [comment]
Its a know issue I also ran into. This is on my list of fixings. Its just
that the upcoming update takes some more time than expected.

The only super you should grant is create database. Than its all fine.

On Fri, Dec 6, 2013 at 7:48 PM, Ben Sparks notifications@github.com wrote:

> there is one spot where it uses MySql EVENTs to monitor the cookies, which
> is part of a plugin, maybe that's it? (it's the connect-mysql in node
> modules / package.json)
> 
> works fine on my system tho (windows)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/367#issuecomment-30018598
> .

## 

---

Lars van der Schans

**Comment by markfarrell** [comment]
Ok. One workaround that I tried was to use a MemoryStore in place of the MySQL store. I rid myself of the previous issue,
but for whatever reason I receive code 500 errors when I try to login as guest. 
e.g
`error saving new random character!Error: ER_BAD_FIELD_ERROR: Unknown column 'lastplayed' in 'field list'`
