### ISSUE TITLE
Server crash when character names contain ALT code characters

### ISSUE THREAD

**Issue by Scottss** [ironbane/IronbaneServerLegacy#409]
Example: Create user with name of "♥♥♥"

Server log:
- World has awaken!
- create character validation failed!  Use alphanumeric characters, - and _ in names only { name: '♥♥♥',
  user: 684,
  creationtime: 1388371375,
  skin: 1004,
  eyes: 1002,
  hair: 1003,
  lastplayed: 1388371375 }
  *29 Dec 19:42:55 - create char error checking for duplicate name: Error: ER_CANT_AGGREGATE_: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
- TypeError: Cannot read property '0' of undefined
  at Query._callback (/opt/ironbane_live/src/server/entity/character.js:155:22)
  at Query.Sequence.end (/opt/ironbane_live/node_modules/mysql/lib/protocol/sequences/Sequence.js:75:24)
  at Query.ErrorPacket (/opt/ironbane_live/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
  at Protocol._parsePacket (/opt/ironbane_live/node_modules/mysql/lib/protocol/Protocol.js:172:24)
  at Parser.write (/opt/ironbane_live/node_modules/mysql/lib/protocol/Parser.js:62:12)
  at Protocol.write (/opt/ironbane_live/node_modules/mysql/lib/protocol/Protocol.js:37:16)
  at Socket.ondata (stream.js:51:26)
  at Socket.EventEmitter.emit (events.js:117:20)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
- error: Forever detected script exited with code: 8
- error: Forever restarting script for 43 time
- starting the server...
- 29 Dec 19:42:55 - starting http server...

**Comment by ingmargoudt** [comment]
fixed, closing
